### ISSUE TITLE
__fork directory creation missing leads to error

### ISSUE THREAD

**Issue by harleyyoung** [aws-samples/service-screener-v2#13]
**Describe the bug**
When I run the screener command:

`screener --regions ap-southeast-1 `

The system reports an error due to a missing __fork directory

**To Reproduce**
Steps to reproduce the behaviour:

1. Set up a new CloudShell in ap-southeast-1
1. Install screener with the following commands
```
python3 -m venv .
source bin/activate
python3 -m pip install --upgrade pip
rm -rf service-screener-v2
git clone https://github.com/aws-samples/service-screener-v2.git
cd service-screener-v2
pip install -r requirements.txt
alias screener="python3 $(pwd)/main.py"
```
1.  Received error due to missing __fork directory
```
(cloudshell-user) [cloudshell-user@ip-10-6-21-223 service-screener-v2]$ screener --regions ap-southeast-1 
 -- Acquiring identify info...
[info] Empty CF stacked created successfully, name:ssv2-3fb1fb9ff47d
Traceback (most recent call last):
  File "/home/cloudshell-user/service-screener-v2/main.py", line 102, in <module>
    files_in_directory = os.listdir(directory)
FileNotFoundError: [Errno 2] No such file or directory: '__fork'
(cloudshell-user) [cloudshell-user@ip-10-6-21-223 service-screener-v2]$ 
```
1. Manually creating the __fork directory allows the program to proceed, but it eventually aborts with the following error:
```
COMPLETED -- IAM::ap-southeast-1 (52.748s)
Total Resources scanned: 51.00 | No. Rules executed: 236.00
Time consumed (seconds): 52.92
CloudtrailpageBuilder class not found, using default pageBuilder
IampageBuilder class not found, using default pageBuilder
Ec2pageBuilder class not found, using default pageBuilder
S3pageBuilder class not found, using default pageBuilder
DynamodbpageBuilder class not found, using default pageBuilder
ElasticachepageBuilder class not found, using default pageBuilder
RdspageBuilder class not found, using default pageBuilder
<S3AccountPublicAccessBlock> not exists in cloudfront.reporter.json
<S3AccountPublicAccessBlock> not exists in cloudfront.reporter.json
Traceback (most recent call last):
  File "/home/cloudshell-user/service-screener-v2/main.py", line 194, in <module>
    Screener.generateScreenerOutput(runmode, contexts, hasGlobal, regions, uploadToS3, bucket)
  File "/home/cloudshell-user/service-screener-v2/Screener.py", line 149, in generateScreenerOutput
    reporter.process(resultSets).getSummary().getDetails()
  File "/home/cloudshell-user/service-screener-v2/services/Reporter.py", line 157, in getSummary
    dashboard['MAP'][self.service][critical] += itemSize
KeyError: 'X'
```

**Expected behavior**
I expect the necessary directory to be created, and for the program to run correctly in order to generate the report

**Screenshots**

**AWS CloudShell (please complete the following information):**
 - Region: [e.g. us-east-1]
 - PHP version [e.g. 7.2]
 - AWS SDK version [e.g. 3.0]
 - Browser (to display output) [e.g. chrome, safari]

**AWS Cloud9 (please complete the following information):**
 - Instance type: [e.g. t2.small]
 - OS: [e.g. Linux]
 - EBS volume size [e.g. 20GiB]
 - Region: [e.g. us-east-1]
 - PHP version [e.g. 7.2]
 - AWS SDK version [e.g. 3.0]
 - Browser (to display output) [e.g. chrome, safari]

**Desktop (please complete the following information):**
 - OS: [e.g. Linux]
 - PHP version [e.g. 7.2]
 - AWS SDK version [e.g. 3.0]
 - Browser (to display output) [e.g. chrome, safari]

**Additional context**

**Comment by kuettai** [comment]
A fixed has been deployed. Please assists to rerun and share with us the results.

**Comment by kuettai** [comment]
Spoke to @harleyyoung , item resolved.
