### ISSUE TITLE
Single az EFS not highlighted

### ISSUE THREAD

**Issue by ensean** [aws-samples/service-screener-v2#141]
**Pick a category**
- [x] New Checks/Rules
- [] New Services coverage
- [] UI improvement
- [] New Features (e.g: new parameter, new filter, new page)
- [] Others...

**Is your feature request related to a problem? Please describe.**
Need to check if any service in my account is deployed in Single AZ, this solution can identify single az RDS/EC Redis successfully, but single az EFS is not identified currently.

**Describe the solution you'd like**
Single AZ EFS should be identified and highlighted in the report

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by kuettai** [comment]
Noted, implementing...

**Comment by kuettai** [comment]
Merged. You may retest :)

**Comment by ensean** [comment]
emmmm, it seems that Single AZ efs is still not identified....

**Comment by kuettai** [comment]
Will take a look again in 3 hours time.

Regards,
KuetTai Yong,
Tel: 0168089925

**Comment by kuettai** [comment]
Meanwhile, make sure you also pull the latest releases.

**Comment by ensean** [comment]
My fault, I specified the wrong region. Confirmed that the single az efs can be highlighted.

<img width="1201" alt="image" src="https://github.com/user-attachments/assets/1b8c6ade-7823-4b71-916f-6af5e964078b">
