### ISSUE TITLE
AttributeError: Module 'os' has no attribute 'move'

### ISSUE THREAD

**Issue by shawn-yinson** [aws-samples/service-screener-v2#17]
**Describe the bug**
Module 'os' has no attribute 'move' error. No output.zip file created after screener completes run.

**To Reproduce**
1. Run script to install dependencies in CloudShell
2. screener --regions ap-southeast-1 

**Expected behavior**
output.zip file is created

**AWS CloudShell (please complete the following information):**
 - Region: ap-southeast-1
 - PHP version [e.g. 7.2]
 - AWS SDK version: aws-cli/2.13.21 Python/3.11.5 Linux/4.14.255-322-265.538.amzn2.x86_64 exec-env/CloudShell exe/x86_64.amzn.2 prompt/off
 - Browser (to display output): Chrome

**Comment by cykhoo0108** [comment]
Issue fixed, please retry.
