### ISSUE TITLE
RDS Scanner Unsupported Operand type

### ISSUE THREAD

**Issue by sheshankgujjari** [aws-samples/service-screener-v2#50]
**Describe the bug**
 File "/home/cloudshell-user/service-screener-v2/services/Evaluator.py", line 28, in run
    getattr(self, method)()
  File "/home/cloudshell-user/service-screener-v2/services/rds/drivers/RdsCommon.py", line 401, in _checkOldSnapshots
    diff = now - oldest_copy_date
TypeError: unsupported operand type(s) for -: 'datetime.date' and 'datetime.datetime'

**To Reproduce**
1. Clone Repo
2. Setup Alias
3. Run command: screener --regions us-east-1 --services rds

**Full commands used to reproduce this bug**
e.g: screener --regions ALL --services rds,iam,ec2
screener --regions us-east-1 --services rds

**Expected behavior**

**Screenshots**

**AWS CloudShell (please complete the following information):**
 - Region: [e.g. us-east-1] us-east-1
 - Python version [e.g. 7.2] Python 3.9.16
 - AWS SDK version (boto3) [e.g. 3.0]
 - Browser (to display output) [e.g. chrome, safari]

**Comment by kuettai** [comment]
Taking a look

**Comment by kuettai** [comment]
Successfully simulated and resolved in #51
