### ISSUE TITLE
Scan the resources based on list of tags

### ISSUE THREAD

**Issue by sheshankgujjari** [aws-samples/service-screener-v2#55]
**Pick a category**

- [] New Features (e.g: new parameter, new filter, new page)

**Is your feature request related to a problem? Please describe.**
No, we have a shared account, we would like to scan the specific resources based on tags

**Describe the solution you'd like**
While running the tool, we would like to pass the list of tags parameter and the tool should scan only the resources mentioned in the tags

**Describe alternatives you've considered**
Not really

**Comment by kuettai** [comment]
Hi @sheshankgujjari , thank you for raising this. Can we know the urgency of this as we plan to look into this feature in Q2.

**Comment by sheshankgujjari** [comment]
It is one of the top priority items for our organization, if this can be addressed ASAP it will help us to pull the reports that are specific to my organization

**Comment by kuettai** [comment]
Acknowledged. Will prioritise this in our sprint.

**Comment by kuettai** [comment]
Resolved in #64 , please look into Example 5 in the readme.
