### ISSUE TITLE
Issue running the service screener

### ISSUE THREAD

**Issue by sames2020** [aws-samples/service-screener-v2#62]
**Describe the bug**
encouter. 
[__!! WARNING !!__] Rule rds::SnapshotTooOld is not available in reporter, please submit an issue to github.

**To Reproduce**
1. Run the following command
python3 -m venv .
source bin/activate
python3 -m pip install --upgrade pip
rm -rf service-screener-v2
git clone https://github.com/aws-samples/service-screener-v2.git
cd service-screener-v2
pip install -r requirements.txt
alias screener="python3 $(pwd)/main.py"
2. Run service screener
screener --regions ALL

**Full commands used to reproduce this bug**
screener --regions ALL

**Expected behavior**
To be able to generated an output. 

**Screenshots**

PREPARING -- CLOUDFRONT::us-east-1
Skipped runtime version check due to unable to locate runtime option path
... (Lambda) inspecting aws-controltower-NotificationForwarder
... (EBS) inspecting vol-03af1b0988a9ff1a1
Skipped runtime version check due to unable to locate runtime option path
... (Lambda) inspecting cwsyn-influasia-heartbeat-341f6852-5ff8-43a9-9888-223a23842bb6
... (EBS) inspecting vol-0136fc860832f318e
... (EBS) inspecting vol-027f8718245a01a10
Skipped runtime version check due to unable to locate runtime option path
... (Lambda) inspecting ECSScheduler
... (EBS) inspecting vol-0ed44c61609253ee4
... (EBS) inspecting vol-059869a83b59a98bf
Skipped runtime version check due to unable to locate runtime option path
... (Lambda) inspecting ecs-task-scheduler-by-tag
... (EBS::Snapshots) inspecting
Skipped runtime version check due to unable to locate runtime option path
... (ELB::Load Balancer) inspecting wof-load-balancer
... (Lambda) inspecting testingecs
... (ELB::Load Balancer) inspecting ALB-common
Skipped runtime version check due to unable to locate runtime option path
COMPLETED -- LAMBDA::ap-southeast-1 (5.004s)
Unable to capture S3 MFA settings: AccessDenied
Unable to capture S3 Logging settings: AccessDenied
IAM Users scan will be skip, unable to acquire IamCredentialReports
DynamodbpageBuilder class not found, using default pageBuilder
S3pageBuilder class not found, using default pageBuilder
EfspageBuilder class not found, using default pageBuilder
OpensearchpageBuilder class not found, using default pageBuilder
CloudfrontpageBuilder class not found, using default pageBuilder
LambdapageBuilder class not found, using default pageBuilder
CloudtrailpageBuilder class not found, using default pageBuilder
EkspageBuilder class not found, using default pageBuilder

[__!! WARNING !!__] Rule rds::SnapshotTooOld is not available in reporter, please submit an issue to github.
Traceback (most recent call last):
  File "/home/cloudshell-user/service-screener-v2/main.py", line 274, in <module>
    Screener.generateScreenerOutput(runmode, contexts, hasGlobal, regions, uploadToS3, bucket)
  File "/home/cloudshell-user/service-screener-v2/Screener.py", line 171, in generateScreenerOutput
    reporter.process(resultSets).getSummary().getDetails()
  File "/home/cloudshell-user/service-screener-v2/services/Reporter.py", line 186, in getSummary
    dashboard['CATEGORY'][region][mainCategory][critical] += itemSize
KeyError: 'X'

**AWS CloudShell (please complete the following information):**
 - Region: us-east-1
 - Python version Python 3.9.1
 - AWS SDK version (boto3) 1.26.165
 - Browser (to display output) chrome

**Additional context**

**Comment by kuettai** [comment]
Acknowledged. Will take a look in next day.

**Comment by kuettai** [comment]
Resolved in #64
