### ISSUE TITLE
Unrecognized arguments --filters

### ISSUE THREAD

**Issue by sheshankgujjari** [aws-samples/service-screener-v2#70]
**Describe the bug**
When I run the latest service screener, getting an error "Screener: error: unrecognized arguments: --filters"

**To Reproduce**
1. Clone Repo
2. Setup Alias
3. Run command

**Full commands used to reproduce this bug**
screener --regions us-east-1 --filters xxx=xxx

**Expected behavior**
It should expect the tag name and value

**Comment by kuettai** [comment]
Will look into this within next 48 hours

**Comment by kuettai** [comment]
@sheshankgujjari , please use **--tags** instead of **--filters**; i updated the readme.MD as well.

**Comment by kuettai** [comment]
Resolved for now.
