### ISSUE TITLE
Tags not supported in this region: [us-east-1], ignoring tags filter

### ISSUE THREAD

**Issue by sheshankgujjari** [aws-samples/service-screener-v2#76]
When do we see this message "Tags not supported in this region: [us-east-1], ignoring tags filter"

**Comment by kuettai** [comment]
This is newly added for error-handling for the previously raise issue. Let me test it in us-east-1 region now.

**Comment by kuettai** [comment]
I am not able to simulate in us-east-1 -region as well. Can you help to check this particular "secretsManager key => Versions => Created On". It might be created on older date when tags is not supported yet.

**Comment by kuettai** [comment]
Closing this item as no further feedback receive.
