### ISSUE TITLE
Unable to generate report

### ISSUE THREAD

**Issue by vfchoopulsifi** [aws-samples/service-screener-v2#8]
**Describe the bug**
screener-v2 throws error after completing inspecting and exits  

**To Reproduce**
1. Run main.py as described with region parameter and output parameter set to report 
2. Error thrown
3. `<EnableCloudTrailLogging> not exists in cloudtrail.reporter.json
<EnableCloudTrailLogging> not exists in cloudtrail.reporter.json
Traceback (most recent call last):
  File "main.py", line 165, in <module>
    Screener.generateScreenerOutput(runmode, contexts, hasGlobal, regions, uploadToS3, bucket)
  File "/home/cloudshell-user/screenerv2/service-screener-v2/Screener.py", line 136, in generateScreenerOutput
    reporter.process(resultSets).getSummary().getDetails()
  File "/home/cloudshell-user/screenerv2/service-screener-v2/services/Reporter.py", line 157, in getSummary
    dashboard['MAP'][self.service][critical] += itemSize
KeyError: 'X
`

**Expected behavior**

**AWS CloudShell (please complete the following information):**
 - Region: ap-southeast-1

**Comment by kuettai** [comment]
Taking a look

**Comment by kuettai** [comment]
Reproduced and Resolved on my end.
