### ISSUE TITLE
DeprecatedSSLProtocolSecurity Inaccurate

### ISSUE THREAD

**Issue by williamnyk** [aws-samples/service-screener-v2#86]
[DeprecatedSSLProtocolSecurity - Your CloudFront distributions are using deprecated SSL protocols for HTTPS communication between CloudFront edge locations and custom origins. Avoid using SSLv3 in your CloudFront distributions.]

This was flagged although the CloudFront distribution origin is using HTTP instead of HTTPS.

**Comment by kuettai** [comment]
Resolved. Please open the ticket if the issue surface again.
