### ISSUE TITLE
High Risk - Group by Service: The pice chart legend should be dynamic instead of static

### ISSUE THREAD

**Issue by williamnyk** [aws-samples/service-screener-v2#87]
UI improvement

The "High Risk - Group by Service" widget shows a fixed legend although the particular service might not contain any High Risk findings at all.

It would be very useful if we could use that widget as a real summary of which services have High Risk issues that need to be remediated.

**Comment by kuettai** [comment]
Development done. Doing a few more rounds of testing before pushing. Estimate to push to prod in next 48 hours.

**Comment by kuettai** [comment]
Resolved.
