### ISSUE TITLE
Text tags error

### ISSUE THREAD

**Issue by apsergithub** [aws-samples/service-screener-v2#9]
**Describe the bug**
In the main screen, "Cost Optimisation" and "Performance Efficieny" are shown, and there's one typo in each one

**To Reproduce**
open a generated report.

**Expected behavior**
"Cost Optimization" and "Performance Efficiency" is the correct text

**Screenshots**

**AWS CloudShell (please complete the following information):**
 - Region: [e.g. us-east-1]
 - PHP version [e.g. 7.2]
 - AWS SDK version [e.g. 3.0]
 - Browser (to display output) [e.g. chrome, safari]

**AWS Cloud9 (please complete the following information):**
 - Instance type: [e.g. t2.small]
 - OS: [e.g. Linux]
 - EBS volume size [e.g. 20GiB]
 - Region: [e.g. us-east-1]
 - PHP version [e.g. 7.2]
 - AWS SDK version [e.g. 3.0]
 - Browser (to display output) [e.g. chrome, safari]

**Desktop (please complete the following information):**
 - OS: [e.g. Linux]
 - PHP version [e.g. 7.2]
 - AWS SDK version [e.g. 3.0]
 - Browser (to display output) [e.g. chrome, safari]

**Additional context**

**Comment by kuettai** [comment]
Taking a look

**Comment by kuettai** [comment]
Reproduced and resolved.
